---
- name: Configure app host
  hosts: all
  become: true
  tasks:
    - name: Sleep for 60 seconds and continue with play
      wait_for:
        timeout: 60

    - name: Install ruby
      apt: "name={{ item }} state=present"
      with_items:
        - ruby-full
        - ruby-bundler
        - build-essential
