---
- name: Configure app host
  hosts: app
  become: true
  tasks:
    - name: Install ruby
      apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
      loop:
          - ruby-full
          - ruby-bundler
          - build-essential
