---
- name: Configure app host
  hosts: db
  become: true
  tasks:
    - name: Add APT key
      apt_key:
        id: EA312927
        keyserver: keyserver.ubuntu.com

    - name: Add APT repository
      apt_repository:
        repo: deb [ arch=amd64,arm64 ] http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.2 multiverse
        state: present

    - name: Install mongodb
      apt:
        name: mongodb-org
        state: present
        update_cache: yes
      notify: run mongod

  handlers:
    - name: start mongod
      systemd: name=mongod state=started
      listen: run mongod
    - name: enable mongod
      systemd: name=mongod state=enabled
      listen: run mongod
